wagov/wasocshared

docs/advisories/20230609002-CL0P-Ransomware-Campaign.md
CL0P Ransomware Campaign - 20230609002
=> Cl0p Ransomware Advisory

docs/advisories/20230612001-Critical-RCE-in-Fortigate-SSL-VPN-devices.md
Fortinet fixes critical RCE in Fortigate SSL-VPN devices - 20230612001
=> Fortinet fixes critical RCE in Fortigate SSL-VPN devices - 20230612001

docs/advisories/20230615003-CISCO-Releases-Security-Advisories-for-Multiple-Products.md, docs/advisories/20230616001-Barracuda-Networks-Releases-Update-to-Address-ESG-Vulnerability.md
=> CISCO Advisory

docs/advisories/20230620003-Sap-High-Severity-Vulnerabilities-June-2023.md
=> 20230620003

docs/baselines/data-sources.md
Added video demonstrating the deployment process and an overall FAQ about the rules.
=> Deployment Walkthrough and FAQ addition

docs/advisories/20230627004-Apple-Security-Updates-Multiple-Products.md
=> Apple-Update-20230627004

docs/advisories/20230630005-D-Link-DIR-859-Router-Command-Execution-Vulnerability.md, docs/advisories/20230630006-D-Link-DWL-2600AP-Access-Point-Command-Injection-Vulnerability.md
=> DLink advisories

docs/advisories/20230714001-SolarView-Compact-Command-Injection-Vulnerability.md
Hi Josh,
Please review and approve my new pull request.
Thanks,
Charles
=> SolarView-Advisory-001

docs/advisories/20230714001-SolarView-Compact-Command-Injection-Vulnerability.md, docs/advisories/20230719001-Citric-Security-Updates.md
Hi Josh,
Please review and approve my new pull request.
Thanks,
Charles
=> Citrix Releases Security Updates 001

docs/advisories/20230728001-Compromised-Microsoft-Key.md, docs/advisories/20230801001-CISA-Releases-IDOR-Vulnerability-Advisory.md
Submitting the advisory "CISA Releases IDOR Vulnerability joint Advisory - 20230801001" on behalf of Jadon Williams, please review and approve
=> CISA Releases IDOR Vulnerability joint Advisory - 20230801001

docs/advisories/20230822004-Citrix-Products-NetScaler-ADC-and-NetScaler-Gateway-Zero-Day-Vulnerability.md
Hi Adon,
Please review and approve my new pull request.
Thanks,
Charles
=> Citrix-Advisory-20230822004

docs/advisories/20230928002-NSA-FBI-CISA-and-Japanese-Partners-Advisory-PRC-Linked-Cyber-Actors.md, docs/guidelines/TTP_Hunt/ADS_forms/T1566.001-QR-CodePhishingAttachment(Quishing).md
NSA, FBI, CISA, and Japanese Partners Release Advisory on PRC-Linked Cyber Actors - 20230928002
=> NSA, FBI, CISA, and Japanese Partners Release Advisory on PRC-Linked Cyber Actors - 20230928002

docs/advisories/20231011002-Adobe-Acrobat-And-Reader-Vulnerability.md
Advisory created for Adobe Use-After-Free vulnerability.
=> Advisory 20231011002

docs/advisories/20231013001-FortiNet-Multiple-Security-Updates.md
Fortinet Releases Security Updates for Multiple Products October 13th
=> Fortinet Releases Security Updates for Multiple Products - 20231013001

docs/training/analyst-induction.md
Removed the mention of free training in the SOC Induction training section.
=> Killed the free

docs/advisories/20231221003-google-chrome-zeroday.md, docs/advisories/20240105001-CISA-adds-two-known-exploited-vulnerabilities-to-catalogue.md
Updated advisories:
- CISA adds two known exploited vulnerabilities to catalogue - 20240105001
- Google Chrome Critical Security Updates - 20231221003
=> Updates to multiple advisories

docs/advisories/20240117003-Google-Chrome-Patch.md
There wasn't much content to add to this advisory so it is a little sparse, let me know if you want me to try pad it out a bit.
=> Google Chrome Zero Day Patch

docs/advisories/20240130001-Juniper-Networks-Security-Advisory.md
=> 20240130001 Juniper Advisory

docs/advisories/20240131002-Mitigation-Defend-Agaist-Exploitation-of-Ivanti.md
New Mitigations to Defend Against Exploitation of Ivanti Connect Secure and Policy Secure Gateways - 20240131002
=> New Mitigations to Defend Against Exploitation of Ivanti Connect Secure and Policy Secure Gateways - 20240131002

docs/advisories/20240131002-Mitigation-Defend-Agaist-Exploitation-of-Ivanti.md, docs/advisories/20240202003-Microsoft-Edge-Security-Update.md
Microsoft Edge Security Updates - 20240202003
=> Microsoft Edge Security Updates - 20240202003

docs/advisories/20240207003-FortiSIEM-Critical-Command-Injection-Vulnerabilities.md
FortiSIEM - Citical Command Injection Vulnerabilities - Advisory @DGovEnterprise
=> FortiSIEM - Citical Command Injection Vulnerabilities Advisory

docs/advisories/20240208003-Cisco-Expressway-Series-Cross_Site-Request-Forgery.md
Cisco Expressway Series Cross-Site Request Forgery Vulnerabilities
=> Cisco Expressway Series Cross-Site Request Forgery Vulnerabilities

docs/advisories/20240207003-FortiSIEM-Critical-Command-Injection-Vulnerabilities.md, docs/advisories/20240209003-Google-Chrome-Security-Updates.md
@DGovEnterprise please review and approve Google Chrome Security Updates Advisory
=> Google Chrome Security Updates Advisory

docs/advisories/20240307002-VMWare-releases-security-advisory-Multiple-Products.md
=> VMware Releases Security Advisory for Multiple Products - 20240307002

docs/advisories/20240308005-Veritas-NetBackup-RCE-Vulnerability.md
A critical vulnerability has been discovered in the Veritas NetBackup servers, clients, and appliance. Successful exploitation could allow an unauthenticated attacker to upload and execute a custom file. CVE-2024-28222.
=> Veritas NetBackup Server and Client RCE Vulnerability - 20240308005

docs/advisories/20240308001-Cisco-Releases-Security-Updates-for-Secure-Client.md
Cisco Releases Security Advisories for Multiple Products - 20240308001
=> Cisco Releases Security Advisories for Multiple Products - 20240308001

docs/advisories/20240313001-Microsoft-Releases-Multiple-Updates.md
=> Microsoft Releases Security Updates for Multiple Products - 20240313001

docs/advisories/20240318004-WordPress-Plugin-FileManager-CriticalVulnerability.md
File Manager And File Manager Pro WordPress Plugin vulnerabilities (9.9 Rating)
=> WP FileManage critical vuln advisory

docs/advisories/20240402005-Linux-Kernel-Vulnerability.md
Linux Kernel Vulnerability - Advisory
@DGovEnterprise , please review and approve.
=> Linux Kernel Vulnerability - Advisory

docs/advisories/20240410004-Adobe-Security-Updates-for-Multiple-Products.md
Didn't follow the standard table format as it would take too long. Some of the products have multiple CVEs related to them
=> 20240410004-Adobe Releases Security Updates for Multiple Products

docs/advisories/20240410001-D-Link-Critical-Vulnerability.md
@DGovEnterprise , please review and approve pull request for d-link critical vulnerability
=> D-link critical vulnerability advisory

docs/advisories/Chrome-Security-Update-20240412001.md
added new. https://wasoc.atlassian.net/browse/SOC-1235730
=> Added - Create Chrome-Security-Update-20240412001.md

docs/advisories/20240410001-D-Link-Critical-Vulnerability.md
=> Revert "20240410001-D-Link-Critical-Vulnerability"

docs/advisories/20240416004-Critical-Rust-Standard-Library-Vulnerability.md
=> 20240416004-Critical-Rust-Standard-Library-Vulnerability

docs/advisories/20240416003-Google-Chrome-V8-Enum-Cache-Out-Of-Bounds-Read-RCE-Vulnerability.md
@DGovEnterprise please review and approve - Advisory - Google Chrome V8 Enum Cache Out-Of-Bounds Read RCE Vulnerability
=> Advisory - Google Chrome V8 Enum Cache Out-Of-Bounds Read RCE Vulnerability

docs/advisories/20240419001-Cisco-Patches-Vulnerabilities-in-Integrated-Management-Controller.md
@DGovEnterprise , please review and approve - Cisco Patches Vulnerabilities in Integrated Management Controller - 20240419001
=> Advisory - Cisco Patches Vulnerabilities in Integrated Management Controller - 20240419001

docs/advisories/20240507002-Xiaomi-Android-Devices-Multiple-Vulnerabilities-Across-Apps-and-System-Components.md
Xiaomi Android Devices Multiple Vulnerabilities Across Apps and System Components - 20240507002
=> Xiaomi Android Devices Multiple Vulnerabilities - 20240507002

docs/advisories/20240508003-Mozilla-Arbitrary-Code-Execution-Vulnerability.md
=> Mozilla PDF.js Arbitrary Code Execution Vulnerability

docs/advisories/20240508001-Google-Android-Security-Advisory-May-2024.md
@DGovEnterprise , PR submitted for Google Android Security Advisory May 2024 -  Advisory. Please review and approve.
=> Google Android Security Advisory May 2024 -  Advisory

docs/advisories/20240510005-Trend-Micro-Patches-Multiple-Vulnerability.md
@DGovEnterprise , PR submitted, please review and approve.
Thanks
=> Trend Micro Patches Multiple Vulnerability - 20240510005 - Advisory

docs/advisories/20240509004-eDrawings-Viewer-DXF-File-Parsing-Out-Of-Bounds-Write-RCE-Vulnerability.md
eDrawings Viewer DXF File Parsing Out-Of-Bounds Write RCE Vulnerability - 20240509004
=> eDrawings Viewer DXF RCE Vulnerability - 20240509004

docs/advisories/20240510002-Deno-Privilege-Escalation.md
CVE-2024-34346 - Deno Privilege Escalation Vulnerability 
CVSS: 8.4
=> Deno Privilege Escalation Vulnerability 

docs/advisories/20240513004-Oracle-VM-VirtualBox-Vulnerability.md
Oracle VM VirtualBox Vulnerability - 20240513004
=> Oracle VM VirtualBox Vulnerability - 20240513004

docs/advisories/20240515001-Apple-Security-Updates-for-Multiple-Products.md
@adonm , please review and approve
Apple Security Updates for Multiple Products - 20240515001
=> Apple Security Updates for Multiple Products - 20240515001 - advisory

docs/advisories/20240515003-Mozilla-Products-Arbitrary-Code-Execution-Multiple-Vulnerabilities md
Mozilla Products Arbitrary Code Execution Multiple Vulnerabilities - 20240515003
=> Mozilla Products Arbitrary Code Execution Multiple Vulnerabilities - 20240515003

docs/advisories/20240520001-Zabbix-SQLi-Vulnerability.md
@DGovEnterprise PR submitted for Zabbix SQLi Vulnerability - 20240520001 - Advisory
Please review and approve
=> Zabbix SQLi Vulnerability - 20240520001 - Advisory

docs/advisories/20240523004-Atlassian-Patches-RCE-Flaw-in-Confluence-Data-Center-and-Server.md
Atlassian Patches RCE Flaw in Confluence Data Center and Server - 20240523004
=> Atlassian RCE in Confluence Data Center and Server - 20240523004

docs/advisories/20240524002-GitLab-Account-Takeover.md
CVE-2024-4835: GitLab Fixes Account Takeover Vulnerability
=> GitLabVuln

docs/advisories/20240523004-Atlassian-Patches-RCE-Flaw-in-Confluence-Data-Center-and-Server.md, docs/advisories/20240605002-macOS-Root-Access-Exploit-Published.md
macOS Root Access Exploit Published - 20240605002
=> macOS Root Access Exploit Published - 20240605002

docs/advisories/20240605001-MySQL2-Vulnerability.md
@DGovEnterprise PR submitted for MySQL2 Vulnerability - 20240605001 - Advisory
Please review and approve
=> MySQL2 Vulnerability - 20240605001 - Advisory

docs/advisories/20240611002-Veeam-PoC-Released.md
Updated product list, as well as relevant wording.
=> 20240611002 - Updated POC information

docs/advisories/20240613001-Google-Chrome-Security-Updates.md
Google Chrome Security Updates - 20240613001
=> Google Chrome Security Updates - 20240613001

docs/advisories/20240617002-Dropbox-Desktop-Mark-of-the-Web-Bypass-Vulnerability.md
Updated this advisory with product affected version.
=> Updated this advisory with product affected version

docs/advisories/20240617002-Dropbox-Desktop-Mark-of-the-Web-Bypass-Vulnerability.md, docs/advisories/20240619003-Deep-Java-Library-Critical-Vulnerability.md
20240617002 - Update of Affected Product information.
20240619003 - Title update to remove double hash
=> Advisory content updates

docs/advisories/20240617002-Dropbox-Desktop-Mark-of-the-Web-Bypass-Vulnerability.md, docs/advisories/20240626004-JavaScript-Polyfill-Supply-Chain-Attack.md
JavaScript Polyfill Supply Chain Attack
=> JavaScript Polyfill Supply Chain Attack

docs/advisories/20240617002-Dropbox-Desktop-Mark-of-the-Web-Bypass-Vulnerability.md, docs/advisories/20240626004-JavaScript-Polyfill-Supply-Chain-Attack.md
=> Updated Polyfill Info. 

docs/advisories/20240628001-GitLab-Vulnerabilities-June-2024r.md
GitLab CVE-2024-5655, CVE-2024-4901, CVE-2024-4994, CVE-2024-6323
=> GitLab June 2024 Vulnerabilities

docs/advisories/20240701001-Juniper-Releases-Urgent-Advisory.md
Juniper Releases Urgent Advisory - 20240701001
=> Juniper Releases Urgent Advisory - 20240701001

docs/advisories/20240702002-Cisco-NX-OS-Vulnerability.md, docs/advisories/20240703002-CISA-New-ICS-Advsories.md, docs/markdown-templates/advisory-CISA-ICS-Advisories.md
20240702002: Update of existing advisory content
20240703002: New Advisory
=> 20240702002 + 20240703002

docs/advisories/20240709002-Synology-Camera-Advisory.md
Advisory for multiple Synology camera vulnerabilities.
=> Synology Cameras

docs/advisories/20240709001-Cisco-Affected-by-OpenSSH-Vulnerability.md
Cisco Affected by OpenSSH Vulnerability
=> Cisco Affected by OpenSSH Vulnerability

docs/advisories/20240710002-Microsoft-Azure-Network-Watcher-VM-Vulnerability.md
=> Microsoft Azure Network Watcher VM Vulnerability - 20240710002

docs/advisories/20240715001-Juniper-Security-Bulletin.md
Noticed that I didn't finish typing out the heading. Have added this in
=> 20240715001 Fix heading

docs/advisories/20240718006-SolarWinds-Patches-Critical-Vulnerabilities.md
SolarWinds Patches Critical Vulnerabilities - 20240718006
=> SolarWinds Patches Critical Vulnerabilities - 20240718006

docs/advisories/20240724003-CISA-Publishes-New-ICS-Advisories.md
@JadonWill PR submitted for CISA Publishes New ICS Advisories - 20240724003 - Advisory
Please review and approve.
=> CISA Publishes New ICS Advisories - 20240724003 - Advisory

docs/advisories/20240725002-Docker-Releases-Critical-Security-Advisory.md
=> 20240725002 - Update

docs/advisories/20240726003-GitLab-Releases-Security-Advisory.md
=> 20240726003 - Update

docs/advisories/20240729001-Acronis-Releases-Critical-Security-Advisory.md
Acronis Releases Critical Security Advisory - 20240729001
=> Acronis Releases Critical Security Advisory - 20240729001

docs/advisories/20240802001-Bitdefender-Releases-Critical-Security-Updates.md
Bitdefender Releases Critical Security Updates - 20240802001
=> Bitdefender Releases Critical Security Updates - 20240802001

docs/advisories/20240809001-Cisco-Releases-Critical-Update.md
@JadonWill PR Submitted for Cisco Releases Critical Update - 20240809001
Please review and approve.
=> Advisory - Cisco Releases Critical Update - 20240809001

docs/advisories/20240814002-SolarWinds-Releases-Critical-Update.md, docs/advisories/20240814003-SAP-Releases-Critical-Updates.md
Update recommendations from "1 month" to "48 hours" to align with E8 Patch Management ML1.
=> 20240814 002 + 003 update

docs/advisories/20240814001-Microsoft-Discloses-Multiple-ZeroDay-Vulnerabilities.md
Microsoft Discloses Multiple ZeroDay Vulnerabilities - 20240814001
=> Microsoft Discloses Multiple ZeroDay Vulnerabilities - 20240814001

docs/advisories/20240814001-Microsoft-Discloses-Multiple-ZeroDay-Vulnerabilities.md
Included CVEs with 'Critical' rating.
Added "Change Log" heading for transparency.
=> 20240814001 Update

docs/guidelines/further-five.md
Updating the links in our site that points to deprecated contents from ACSC
=> PR for changes to further five

docs/advisories/20240826001-Chromium-Vulnerability-Known-Exploitation.md
=> Chromium Vulnerability Known Exploitation - 20240826001

docs/advisories/20240911002-Ivanti-Publishes-Critical-Security-Updates.md
20240911002 - Ivanti Publishes Critical Security Updates
=> 20240911002 - Ivanti Publishes Critical Security Updates

docs/advisories/20240926001-SQL-Critical-Vulnerabilities.md
Please review SQL-based Critical Vulnerabilities - 20240926001
=> SQL-based Critical Vulnerabilities - 20240926001

docs/advisories/20241001001-SolarWinds-Critical-Vulnerability.md
SolarWinds Critical Vulnerability - 20241001001
=> SolarWinds Critical Vulnerability - 20241001001

docs/advisories/20240926001-SQL-Critical-Vulnerabilities.md, docs/advisories/20241002001-CISA-ICS-Advisories.md
Please review CISA Releases New ICS Advisories - 20241002001
=> CISA Releases New ICS Advisories - 20241002001

docs/advisories/20241015001-Java-deserialization-vulnerability.md
Java deserialization vulnerability
=> Java deserialization vulnerability

docs/advisories/20241015001-Java-deserialization-vulnerability.md
=> Edited to fix Syntax Error

docs/advisories/20241021003-CISA-New-ICS-Advisories.md
=> 20241021003-CISA-NEW-ICS-Advisories

docs/advisories/20241024001-Microsoft-Sharepoint-Server-Vulnerability.md
Microsoft SharePoint Vulnerability Added in CISA Known Exploits
=> Microsoft SharePoint Vulnerability Added in CISA Known Exploits

docs/advisories/20241021003-CISA-New-ICS-Advisories.md, docs/advisories/20241029001-Progress-WhatsUp-Critical-Update.md
=> 20241029001-Progress-WhatsUp-Critical-Update

docs/advisories/20241030004-New-ICS-Advisories.md
=> 20241030004

docs/advisories/20241101002-New-ICS-Advisories.md
@JadonWill please review and approve
=> New ICS Advisories - 20241101002

docs/advisories/20241105001-Ricoh-Critical-Update.md, docs/advisories/20241105001-Ricoh-Critical-Updates.md
=> 20241105001-Ricoh-Critical-Update

docs/advisories/20241121001-Apache-OfBiz-Critical-Update.md
Apache OfBiz Critical Update - 20241121001
=> Apache OfBiz Critical Update - 20241121001

docs/advisories/202411212001-Veritas-Critical-Vulnerability.md
@JadonWill PR submitted, please review and approve.
=> Veritas Critical Vulnerability - 20241122001

docs/advisories/20241122002-New-ICS-Advisories.md
=> Advisory 20241122002

docs/advisories/20241205001-Veeam-Critical-Advisory.md
20241205001 - Veeam Critical Advisory
=> Veeam Advisory

docs/advisories/20241213002-Apache-Struts-Critical-Vulnerability.md
=> 20241213002

docs/advisories/20241218001-CISA-Releases-Five-ICS-Advisories.md
CISA Releases Five ICS Advisories - 20241218001
=> CISA Releases Five ICS Advisories - 20241218001

docs/advisories/20241219001-Apache-Tomcat-Critical-Vulnerability.md
@JadonWill PR has been submitted for "Apache Tomcat Critical Vulnerability - 20241219001". Please review and approve.
=> Apache Tomcat Critical Vulnerability - 20241219001

docs/advisories/20241223001-Fortinet-Security-Updates-for-FortiManager.md
Fortinet Security Updates for FortiManager - 20241223001
=> Fortinet Security Updates for FortiManager - 20241223001

docs/advisories/20241219001-Apache-Tomcat-Critical-Vulnerability.md, docs/advisories/20241223002-Sophos-Firewall-Addresses-Multiple-Vulnerabilities.md
PR submitted "Sophos Firewall Addresses Multiple Vulnerabilities - 20241223002", please review and approve.
=> Sophos Firewall Addresses Multiple Vulnerabilities - 20241223002

docs/advisories/20241230001-PAN-OS-Vulnerability-Now-Exploited-in-the-Wild.md
@DamoOne , PR has been submitted for "PAN-OS Vulnerability Now Exploited in the Wild - 20241230001". Please review and approve.
=> PAN-OS Vulnerability Now Exploited in the Wild - 20241230001

docs/advisories/20250110002-OpenVPN-Critical-Vulnerability.md
OpenVPN Critical Vulnerability - 20250110002
=> OpenVPN Critical Vulnerability - 20250110002

docs/advisories/20250117001-CISA-ICS-Advisories.md
@JadonWill , pull request submitted, please review and approve.
=> CISA Releases New ICS Advisories - 20250117001

docs/advisories/20250128003-SonicWall-Critical-Vulnerability.md
SonicWall Critical Vulnerability - 20250128003
=> SonicWall Critical Vulnerability - 20250128003

docs/advisories/20250128001-Apple-Known-Exploited-Vulnerability.md
PR submitted with updated CVSS
=> 20250128001-Apple-Known-Exploited-Vulnerability

docs/advisories/20250205002-New-ICS-Advisories.md
New ICS Advisories - 20250205002
=> New ICS Advisories - 20250205002

docs/advisories/20250205003-CISA-Known-Exploited-Vulnerabilities.md
@DamoOne, PR submitted for "CISA Adds Known Exploited Vulnerabilities to Catalog - 20250205003", please review and approve.
=> CISA Adds Known Exploited Vulnerabilities to Catalog - 20250205003

docs/advisories/20250206001-CISA-Adds-One-Known-Exploited-Vulnerability.md
=> 20250206001-CISA-Adds-One-Known-Exploited-Vulnerability

docs/onboarding/honey-traps.md
Fixed a typo in the document note.
=> Fixed typo

docs/advisories/20250221003-Citrix-Addresses-Authenticated-Privilege-Escalation-Vulnerability-in-NetScale.md, docs/onboarding/honey-traps.md
Citrix Addresses Authenticated Privilege Escalation Vulnerability in NetScale - 20250221003
=> Citrix Addresses Authenticated Privilege Escalation Vulnerability in NetScale - 20250221003

docs/advisories/20250221002-Microsoft-fixes-Power-Pages-zero-day-bug-exploited-in-attacks.md, docs/advisories/20250221003-Citrix-Addresses-Authenticated-Privilege-Escalation-Vulnerability-in-NetScale.md
@DGovEnterprise , please review and approve.
Thanks
=> Microsoft Fixes Power Pages Zero-day Bug Exploited in Attacks - 20250221002

.github/workflows/tlpclear-testing.yml, docs/onboarding.md
=> Updated Docuements and Fix MKFormat issues

docs/advisories/20250304001-CISA-Known-Exploited-Vulnerabilities.md
=> Advisory 20250304001

docs/advisories/20250310001-CISA-New-ICS-Advisories.md
=> Advisory 20250310001 - Targeted - CISA New ICS Advisories

docs/advisories/20250318001-Apache-Tomcat-RCE-Vulnerability.md
=> Update for Base Score

docs/advisories/20250325001-Ingress-NGINX-Critical-Vulnerability.md
Ingress NGINX Critical Vulnerability - 20250325001
=> Ingress NGINX Critical Vulnerability - 20250325001

docs/advisories/20250325002-NextJS-Auth-Bypass.md, docs/markdown-templates/Advisory-vulnerability.md, docs/markdown-templates/advisory-KnownExploited.md
Templates updated to remove specific timeframes, and to instead refer to the published guidelines.
=> 20250325002 & template updates

docs/markdown-templates/Advisory-vulnerability.md, docs/markdown-templates/advisory-KnownExploited.md
Update of wording to reflect "no reports of", as opposed to "no detections of".
=> Template updates - What has been observed

docs/advisories/20250328001-Mozilla-Critical-Advisory.md
Mozilla Critical Advisory - 20250328001
=> Mozilla Critical Advisory - 20250328001

docs/advisories/20250409003-SAP-Critical-Updates.md
@JadonWill , PR submitted, please review and approve.
=> SAP Critical Updates - 20250409003

docs/advisories/20250409002-Fortinet-Critical-Vulnerability.md
Fortinet Critical Vulnerability - 20250409002
=> Fortinet Critical Vulnerability - 20250409002

docs/advisories/20250318001-Apache-Tomcat-RCE-Vulnerability.md, docs/advisories/20250409001-Microsoft-April-Patch.md
=> Ms April 2025 Patch

docs/advisories/20250409004-Critical-Siemens-Vulnerabilities.md
=> 20250409004-Critical-Siemens-Vulnerabilities

docs/advisories/20250424001-Commvault-Critical-Vulnerability.md
@JadonWill , PR submitted, please review and approve.
=> Commvault Critical Vulnerability - 20250424001

docs/advisories/20250428001-SAP-Critical-Vulnerabilities.md
=> 20250428001-SAP-Critical-Vulnerabilities

docs/onboarding/honey-traps.md
Minor updates to fix typos etc
=> Updated the Honey Trap Pilot page content

docs/advisories/20250428001-SAP-Critical-Vulnerabilities.md, docs/advisories/20250502001-Apache-ActiveMQ-Vulnerability.md
=> 20250502001-Apache-ActiveMQ-Vulnerability

mkdocs.yml
Adding in the Playbooks page in the guidelines section of the side nav bar.
=> Playbooks in Nav

docs/advisories/20250611002-SAP-Critical-Vulnerability.md
=> 20250611002-SAP-Critical-Vulnerability

docs/advisories/20250617001-Google-Chrome-Zero-Day-Vulnerability.md
=> 20250617001-Google-Chrome-Zero-Day-Vulnerability

docs/advisories/202507023001-Cisco-Unified-Communications-Manager-Vulnerability.md
@DamoOne PR submitted for Cisco Unified Communications Manager Vulnerability, please review and approve.
=> Cisco Unified Communications Manager Vulnerability

docs/advisories/20250709002-Fortinet-Critical-Update.md
=> 20250709002-Fortinet-Critical-Update

docs/advisories/20250716001-Broadcom-Critical-Updates.md
PR submitted for Broadcom Critical Updates - 20250716001
=> Broadcom Critical Updates - 20250716001

docs/advisories/20250716002-Oracle-Critical-Updates.md
=> 20250716002-Oracle-Critical-Updates

docs/advisories/20250725002-Mitel-Critical-Vulnerability.md
=> 20250725002-Mitel-Critical-Vulnerability

docs/advisories/20250725001-New-ICS-Critical-Vulnerabilities.md
New ICS Critical Vulnerabilities - 20250725001
=> New ICS Critical Vulnerabilities - 20250725001

docs/advisories/20250806004 -CISA-ICS-Critical-Vulnerability.md, docs/markdown-templates/Advisory-vulnerability.md
Pull request submission for CISA-ICS-Critical-Vulnerability-20250806004
=> 20250806004

docs/advisories/20250813003-Fortinet-Critical-Vulnerability.md
=> 20250813003-Fortinet-Critical-Vulnerability

docs/advisories/20250806001-Trend-Micro-Critical-Vulnerability.md
PR submitted, added into Kev @DamoOne
=> 20250806001-Trend-Micro-Critical-Vulnerability

docs/advisories/20250825003-Tableau-Critical-Vulnerability.md
@JadonWill , PR submitted please review and approve.
=> Tableau Critical Vulnerability - 20250825003
